version: '3'

services:
  prometheus:
    build: ./prometheus
    ports:
      - "9090:9090"
    volumes:
      - /home/vagrant/sincro:/etc/prometheus

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
